name: PHPStan - Level 10

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Cache Composer
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-php-8.2-${{ hashFiles('**/composer.lock', '**/tests/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-8.2

      - name: Install root dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Install test dependencies
        run: cd tests && composer install --no-interaction --prefer-dist

      - name: Run PHPUnit
        run: make phpstan