name: PHPUnit

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.2', '8.3', '8.4']

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock', '**/tests/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-${{ matrix.php.version }}-

      - name: Install root dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Install test dependencies
        working-directory: tests
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPUnit
        run: make phpunit